from .base import Connection

class PoolingConnection(Connection):
    def _make_connection(self) -> Connection: ...
    def _get_connection(self) -> Connection: ...
    def _release_connection(self, con: Connection) -> None: ...
    def close(self) -> None: ...
